import type {
  DashboardOptions,
  Task,
  KPICard,
  KPIGroup,
  Bottleneck,
  TodoItem,
  FunnelDetailData,
} from "./types";
import { toISODate } from "./utils";

function relDate(offset: number): string {
  const d = new Date();
  d.setDate(d.getDate() + offset);
  return toISODate(d);
}

export const defaultOptions: DashboardOptions = {
  importance: [
    { id: "imp-high", label: "높음", color: "#EF4444" },
    { id: "imp-mid", label: "중간", color: "#F59E0B" },
    { id: "imp-low", label: "낮음", color: "#10B981" },
  ],
  status: [
    { id: "st-wait", label: "대기", color: "#6B7280" },
    { id: "st-inprog", label: "진행중", color: "#3B82F6" },
    { id: "st-done", label: "완료", color: "#10B981" },
    { id: "st-hold", label: "보류", color: "#F59E0B" },
  ],
  assignees: [
    { id: "usr-heidi", label: "헤이디", color: "#EC4899" },
    { id: "usr-rudd", label: "러드", color: "#3B82F6" },
    { id: "usr-woody", label: "우디", color: "#8B5CF6" },
  ],
  funnels: [
    { id: "fn-plan", label: "강의 기획 단계", color: "#6366F1" },
    { id: "fn-recruit", label: "무료 강의 인원 모집", color: "#3B82F6" },
    { id: "fn-kakao", label: "모집 인원 단톡방 관리", color: "#06B6D4" },
    { id: "fn-free", label: "무료 강의 진행", color: "#10B981" },
    { id: "fn-paid", label: "유료 강의 운영", color: "#F59E0B" },
  ],
};

export const mockTasks: Task[] = [
  {
    id: "task-1",
    content: "강의 커리큘럼 설계 및 목차 확정",
    importanceId: "imp-high",
    statusId: "st-inprog",
    assigneeId: "usr-heidi",
    comment: "12주 커리큘럼 기준 주차별 학습 목표 및 과제 설계 필요.",
    startDate: relDate(-14),
    dueDate: relDate(7),
    funnelId: "fn-plan",
    createdAt: relDate(-20),
  },
  {
    id: "task-2",
    content: "강의 자료(PPT/영상) 제작",
    importanceId: "imp-high",
    statusId: "st-inprog",
    assigneeId: "usr-rudd",
    comment: "주차별 슬라이드 및 실습 예제 제작. 현재 5주차까지 완료.",
    startDate: relDate(-10),
    dueDate: relDate(14),
    funnelId: "fn-plan",
    createdAt: relDate(-15),
  },
  {
    id: "task-3",
    content: "SNS 광고 캠페인 기획 및 소재 제작",
    importanceId: "imp-high",
    statusId: "st-done",
    assigneeId: "usr-woody",
    comment: "인스타그램/페이스북 광고 소재 A/B 3세트 완료.",
    startDate: relDate(-30),
    dueDate: relDate(-5),
    funnelId: "fn-recruit",
    createdAt: relDate(-35),
  },
  {
    id: "task-4",
    content: "무료 강의 신청 랜딩 페이지 제작",
    importanceId: "imp-high",
    statusId: "st-inprog",
    assigneeId: "usr-heidi",
    comment: "신청 폼 최적화 및 CTA 버튼 A/B 테스트 진행 중.",
    startDate: relDate(-7),
    dueDate: relDate(21),
    funnelId: "fn-recruit",
    createdAt: relDate(-10),
  },
  {
    id: "task-5",
    content: "단톡방 운영 가이드라인 수립",
    importanceId: "imp-mid",
    statusId: "st-done",
    assigneeId: "usr-rudd",
    comment: "공지 주기, 질문 응답 규칙, 이탈 방지 전략 문서 완성.",
    startDate: relDate(-20),
    dueDate: relDate(-8),
    funnelId: "fn-kakao",
    createdAt: relDate(-25),
  },
  {
    id: "task-6",
    content: "단톡방 일일 콘텐츠 스케줄 운영",
    importanceId: "imp-mid",
    statusId: "st-inprog",
    assigneeId: "usr-woody",
    comment: "오전 동기부여 메시지, 오후 학습 팁 등 일일 2회 발행 중.",
    startDate: relDate(-5),
    dueDate: relDate(25),
    funnelId: "fn-kakao",
    createdAt: relDate(-8),
  },
  {
    id: "task-7",
    content: "무료 강의 줌(Zoom) 세션 운영",
    importanceId: "imp-high",
    statusId: "st-inprog",
    assigneeId: "usr-heidi",
    comment: "매주 화/목 20:00 라이브 강의 진행. 참석자 Q&A 포함.",
    startDate: relDate(-3),
    dueDate: relDate(18),
    funnelId: "fn-free",
    createdAt: relDate(-5),
  },
  {
    id: "task-8",
    content: "무료 강의 완주 인증 시스템 구축",
    importanceId: "imp-mid",
    statusId: "st-wait",
    assigneeId: "usr-rudd",
    comment: "과제 제출 → 완주 인증서 발급 자동화 파이프라인 설계 필요.",
    startDate: relDate(5),
    dueDate: relDate(30),
    funnelId: "fn-free",
    createdAt: relDate(-3),
  },
  {
    id: "task-9",
    content: "유료 강의 세일즈 페이지 제작",
    importanceId: "imp-high",
    statusId: "st-done",
    assigneeId: "usr-woody",
    comment: "수강 후기, 커리큘럼, 강사 소개, FAQ 섹션 완성. CTA 최적화 완료.",
    startDate: relDate(-25),
    dueDate: relDate(-10),
    funnelId: "fn-paid",
    createdAt: relDate(-28),
  },
  {
    id: "task-10",
    content: "유료 강의 얼리버드 프로모션 설계",
    importanceId: "imp-high",
    statusId: "st-hold",
    assigneeId: "usr-heidi",
    comment: "할인 정책 및 기간 확정 대기 중. 법무 검토 완료 후 재개.",
    startDate: relDate(20),
    dueDate: relDate(50),
    funnelId: "fn-paid",
    createdAt: relDate(-1),
  },
  {
    id: "task-11",
    content: "수강생 후기 및 성과 사례 수집",
    importanceId: "imp-mid",
    statusId: "st-wait",
    assigneeId: "usr-rudd",
    comment: "무료 강의 완주생 대상 인터뷰 및 후기 영상 촬영 계획.",
    startDate: relDate(15),
    dueDate: relDate(40),
    funnelId: "fn-paid",
    createdAt: relDate(-1),
  },
  {
    id: "task-12",
    content: "유료 전환 이메일 시퀀스 작성",
    importanceId: "imp-mid",
    statusId: "st-inprog",
    assigneeId: "usr-woody",
    comment: "무료 강의 완주 후 7일 드립 캠페인 (5통). 현재 3통 완성.",
    startDate: relDate(-3),
    dueDate: relDate(18),
    funnelId: "fn-paid",
    createdAt: relDate(-5),
  },
];

export const defaultKPIGroups: KPIGroup[] = [
  {
    id: "group-free",
    label: "무료 강의 퍼널",
    cards: [
      {
        id: "kpi-1",
        title: "총 무료 강의 신청자",
        value: "324명",
        change: 8.0,
        changeLabel: "전기 대비",
        icon: "Users",
        color: "#3B82F6",
        bgColor: "rgba(59,130,246,0.1)",
      },
      {
        id: "kpi-5",
        title: "무료 강의 완주율",
        value: "68%",
        change: -5.0,
        changeLabel: "전기 대비 -5%p",
        icon: "Target",
        color: "#06B6D4",
        bgColor: "rgba(6,182,212,0.1)",
      },
      {
        id: "kpi-6",
        title: "평균 만족도",
        value: "4.3 / 5.0",
        change: 0.2,
        changeLabel: "전기 대비 +0.2점",
        icon: "Star",
        color: "#EC4899",
        bgColor: "rgba(236,72,153,0.1)",
      },
    ],
  },
  {
    id: "group-paid",
    label: "유료 결제 퍼널",
    cards: [
      {
        id: "kpi-2",
        title: "유료 전환율",
        value: "23%",
        change: 3.0,
        changeLabel: "전기 대비 +3%p",
        icon: "TrendingUp",
        color: "#10B981",
        bgColor: "rgba(16,185,129,0.1)",
      },
      {
        id: "kpi-3",
        title: "총 매출",
        value: "₩3,680,000",
        change: 22.7,
        changeLabel: "전기 대비",
        icon: "DollarSign",
        color: "#F59E0B",
        bgColor: "rgba(245,158,11,0.1)",
      },
      {
        id: "kpi-4",
        title: "ROAS",
        value: "818%",
        change: 15.5,
        changeLabel: "전기 대비",
        icon: "BarChart2",
        color: "#8B5CF6",
        bgColor: "rgba(139,92,246,0.1)",
      },
    ],
  },
];

export const funnelDetails: FunnelDetailData[] = [
  {
    funnelId: "fn-plan",
    summary: "강의 콘텐츠 설계부터 자료 제작까지 강의 출시 전 준비 단계입니다.",
    kpis: [
      { label: "커리큘럼 완성도", value: "85%", target: "100%", achievement: 85, change: 12, changeLabel: "전주 대비", color: "#6366F1" },
      { label: "강의 자료 제작", value: "7주차 / 12주차", target: "12주차", achievement: 58, change: 8, changeLabel: "전주 대비", color: "#6366F1" },
      { label: "강사 섭외 완료", value: "3명", target: "4명", achievement: 75, change: 0, changeLabel: "", color: "#6366F1" },
      { label: "예산 집행률", value: "60%", target: "80%", achievement: 75, change: 5, changeLabel: "전주 대비", color: "#6366F1" },
    ],
    bottlenecks: [
      {
        id: "bn-plan-1",
        stage: "강의 자료 제작",
        issue: "제작 진도 목표 대비 -17%p 지연",
        impact: "high",
        metric: "42% 미완성",
        description: "8~12주차 강의 자료가 미완성 상태. 강사 피드백 반영 사이클이 예상보다 2배 소요되고 있어 제작 일정이 지연되고 있음.",
      },
      {
        id: "bn-plan-2",
        stage: "강사 섭외",
        issue: "섭외 목표 4명 중 1명 미확정",
        impact: "medium",
        metric: "25% 미달",
        description: "게스트 강사 1명 섭외 협의 중. 일정 및 강사료 조율 필요. 미확정 시 해당 주차 콘텐츠 대체안 필요.",
      },
    ],
    todos: [
      { id: "td-plan-1", text: "8~12주차 강의 슬라이드 초안 완성", completed: false, priority: "high", relatedStage: "강의 자료 제작", funnelId: "fn-plan" },
      { id: "td-plan-2", text: "게스트 강사 4번째 섭외 최종 확정", completed: false, priority: "high", relatedStage: "강사 섭외", funnelId: "fn-plan" },
      { id: "td-plan-3", text: "커리큘럼 검토 및 피드백 반영 완료", completed: true, priority: "medium", relatedStage: "커리큘럼", funnelId: "fn-plan" },
      { id: "td-plan-4", text: "실습 예제 코드 깃허브 업로드", completed: false, priority: "medium", relatedStage: "강의 자료 제작", funnelId: "fn-plan" },
    ],
  },
  {
    funnelId: "fn-recruit",
    summary: "SNS 광고 및 랜딩 페이지를 통한 무료 강의 수강생 모집 단계입니다.",
    kpis: [
      { label: "총 신청자", value: "324명", target: "300명", achievement: 108, change: 8, changeLabel: "목표 대비", color: "#3B82F6" },
      { label: "광고 CTR", value: "3.8%", target: "3.0%", achievement: 127, change: 0.4, changeLabel: "전주 대비", color: "#3B82F6" },
      { label: "신청 전환율", value: "2.1%", target: "2.5%", achievement: 84, change: 0.2, changeLabel: "전주 대비", color: "#3B82F6" },
      { label: "광고비 집행", value: "₩450,000", target: "₩500,000", achievement: 90, change: 0, changeLabel: "예산 내 집행", color: "#3B82F6" },
    ],
    bottlenecks: [
      {
        id: "bn-rec-1",
        stage: "신청 전환율",
        issue: "랜딩 페이지 전환율 목표 대비 -0.4%p 미달",
        impact: "medium",
        metric: "84% 달성",
        description: "광고 클릭 후 랜딩 페이지에서 신청 폼까지의 전환율이 낮음. CTA 문구 및 신청 폼 단계 최소화 필요.",
      },
    ],
    todos: [
      { id: "td-rec-1", text: "랜딩 페이지 CTA 문구 A/B 테스트 진행", completed: false, priority: "high", relatedStage: "신청 전환율", funnelId: "fn-recruit" },
      { id: "td-rec-2", text: "신청 폼 필드 수 5개 이하로 축소", completed: true, priority: "high", relatedStage: "신청 전환율", funnelId: "fn-recruit" },
      { id: "td-rec-3", text: "인스타그램 릴스 광고 소재 2종 추가 제작", completed: false, priority: "medium", relatedStage: "광고 CTR", funnelId: "fn-recruit" },
      { id: "td-rec-4", text: "신청 완료 자동 문자 발송 설정", completed: true, priority: "low", relatedStage: "신청 전환율", funnelId: "fn-recruit" },
    ],
  },
  {
    funnelId: "fn-kakao",
    summary: "모집 완료된 수강생들의 단톡방 참여도 유지 및 관리 단계입니다.",
    kpis: [
      { label: "단톡방 참여율", value: "91%", target: "95%", achievement: 96, change: 1, changeLabel: "전주 대비", color: "#06B6D4" },
      { label: "일일 활성 참여율", value: "62%", target: "70%", achievement: 89, change: -2, changeLabel: "전주 대비", color: "#06B6D4" },
      { label: "이탈율", value: "4.2%", target: "5% 이하", achievement: 84, change: 0.8, changeLabel: "전주 대비 개선", color: "#06B6D4" },
      { label: "공지 열람율", value: "78%", target: "85%", achievement: 92, change: 3, changeLabel: "전주 대비", color: "#06B6D4" },
    ],
    bottlenecks: [
      {
        id: "bn-kakao-1",
        stage: "일일 활성 참여율",
        issue: "목표 대비 -8%p 미달",
        impact: "high",
        metric: "62% (목표 70%)",
        description: "단톡방 입장 후 실제 반응(이모지/댓글)하는 비율이 낮음. 콘텐츠 다양성 부족 및 질문 유도 장치 미비.",
      },
      {
        id: "bn-kakao-2",
        stage: "공지 열람율",
        issue: "중요 공지 미열람 22%",
        impact: "low",
        metric: "78% (목표 85%)",
        description: "공지 발송 시간대가 수강생 활동 시간과 불일치. 저녁 8-9시 발송으로 변경 검토 필요.",
      },
    ],
    todos: [
      { id: "td-kakao-1", text: "매일 오전 8시 동기부여 메시지 자동화", completed: false, priority: "high", relatedStage: "일일 활성 참여율", funnelId: "fn-kakao" },
      { id: "td-kakao-2", text: "주 1회 퀴즈/미션 이벤트 도입", completed: false, priority: "high", relatedStage: "일일 활성 참여율", funnelId: "fn-kakao" },
      { id: "td-kakao-3", text: "공지 발송 시간 저녁 8시로 변경", completed: true, priority: "medium", relatedStage: "공지 열람율", funnelId: "fn-kakao" },
      { id: "td-kakao-4", text: "우수 참여자 주간 인증 제도 운영", completed: false, priority: "low", relatedStage: "일일 활성 참여율", funnelId: "fn-kakao" },
    ],
  },
  {
    funnelId: "fn-free",
    summary: "모집된 수강생 대상 무료 강의를 실제로 진행하는 단계입니다.",
    kpis: [
      { label: "평균 출석율", value: "76%", target: "80%", achievement: 95, change: -2, changeLabel: "전주 대비", color: "#10B981" },
      { label: "강의 완주율", value: "68%", target: "75%", achievement: 91, change: -3, changeLabel: "전주 대비", color: "#10B981" },
      { label: "수강생 만족도", value: "4.3점", target: "4.5점", achievement: 96, change: 0.1, changeLabel: "전주 대비", color: "#10B981" },
      { label: "Q&A 응답률", value: "94%", target: "90%", achievement: 104, change: 2, changeLabel: "전주 대비", color: "#10B981" },
    ],
    bottlenecks: [
      {
        id: "bn-free-1",
        stage: "강의 완주율",
        issue: "목표 대비 -7%p 미달",
        impact: "high",
        metric: "68% (목표 75%)",
        description: "3~4주차 이후 중도 이탈 증가. 강의 내용 난이도 급상승 구간에서 이탈 집중 발생. 중간 점검 및 개인 피드백 세션 필요.",
      },
      {
        id: "bn-free-2",
        stage: "평균 출석율",
        issue: "목표 대비 -4%p",
        impact: "medium",
        metric: "76% (목표 80%)",
        description: "화요일 강의 출석율이 목요일 대비 10%p 낮음. 화요일 시간대 재검토 또는 녹화 영상 제공 검토 필요.",
      },
    ],
    todos: [
      { id: "td-free-1", text: "3~4주차 난이도 구간 보충 자료 제공", completed: false, priority: "high", relatedStage: "강의 완주율", funnelId: "fn-free" },
      { id: "td-free-2", text: "화요일 강의 시간 저녁 8시로 변경", completed: false, priority: "high", relatedStage: "출석율", funnelId: "fn-free" },
      { id: "td-free-3", text: "중도 이탈자 대상 1:1 DM 재참여 유도", completed: true, priority: "medium", relatedStage: "완주율", funnelId: "fn-free" },
      { id: "td-free-4", text: "강의 녹화본 24시간 내 업로드 자동화", completed: false, priority: "medium", relatedStage: "출석율", funnelId: "fn-free" },
      { id: "td-free-5", text: "만족도 5점 수강생 후기 영상 촬영 섭외", completed: false, priority: "low", relatedStage: "만족도", funnelId: "fn-free" },
    ],
  },
  {
    funnelId: "fn-paid",
    summary: "무료 강의 완주생을 대상으로 유료 강의로 전환하고 운영하는 단계입니다.",
    kpis: [
      { label: "유료 전환율", value: "23%", target: "25%", achievement: 92, change: 3, changeLabel: "전기 대비", color: "#F59E0B" },
      { label: "총 매출", value: "₩3,680,000", target: "₩3,000,000", achievement: 123, change: 22.7, changeLabel: "전기 대비", color: "#F59E0B" },
      { label: "ROAS", value: "818%", target: "700%", achievement: 117, change: 15.5, changeLabel: "전기 대비", color: "#F59E0B" },
      { label: "유료 수강 완주율", value: "71%", target: "75%", achievement: 95, change: 2, changeLabel: "전기 대비", color: "#F59E0B" },
    ],
    bottlenecks: [
      {
        id: "bn-paid-1",
        stage: "유료 전환율",
        issue: "목표 대비 -2%p 미달",
        impact: "medium",
        metric: "92% 달성",
        description: "무료 강의 완주 후 유료 전환 설득력 부족. 수강 후기 및 성과 사례 콘텐츠 보강 필요. 얼리버드 프로모션 미출시 영향.",
      },
    ],
    todos: [
      { id: "td-paid-1", text: "무료 강의 완주생 대상 유료 전환 이메일 시퀀스 발송", completed: false, priority: "high", relatedStage: "유료 전환율", funnelId: "fn-paid" },
      { id: "td-paid-2", text: "얼리버드 30% 할인 프로모션 기간 확정", completed: false, priority: "high", relatedStage: "유료 전환율", funnelId: "fn-paid" },
      { id: "td-paid-3", text: "수강생 성과 사례 3건 세일즈 페이지 업로드", completed: true, priority: "medium", relatedStage: "유료 전환율", funnelId: "fn-paid" },
      { id: "td-paid-4", text: "유료 수강생 전용 커뮤니티(단톡방) 개설", completed: false, priority: "medium", relatedStage: "유료 수강 완주율", funnelId: "fn-paid" },
      { id: "td-paid-5", text: "수강 완주 시 수료증 발급 자동화", completed: false, priority: "low", relatedStage: "유료 수강 완주율", funnelId: "fn-paid" },
    ],
  },
];

// Flatten all todos for global use
export const initialTodos: import("./types").TodoItem[] = funnelDetails.flatMap(
  (fd) => fd.todos
);
