import type {
  DashboardOptions,
  Task,
  KPICard,
  FunnelStage,
  Bottleneck,
  TodoItem,
} from "./types";
import { toISODate } from "./utils";

function relDate(offset: number): string {
  const d = new Date();
  d.setDate(d.getDate() + offset);
  return toISODate(d);
}

export const defaultOptions: DashboardOptions = {
  importance: [
    { id: "imp-high", label: "높음", color: "#EF4444" },
    { id: "imp-mid", label: "중간", color: "#F59E0B" },
    { id: "imp-low", label: "낮음", color: "#10B981" },
  ],
  status: [
    { id: "st-wait", label: "대기", color: "#6B7280" },
    { id: "st-inprog", label: "진행중", color: "#3B82F6" },
    { id: "st-done", label: "완료", color: "#10B981" },
    { id: "st-hold", label: "보류", color: "#F59E0B" },
  ],
  assignees: [
    { id: "usr-1", label: "김민준", color: "#8B5CF6" },
    { id: "usr-2", label: "이서연", color: "#EC4899" },
    { id: "usr-3", label: "박지호", color: "#06B6D4" },
    { id: "usr-4", label: "최유진", color: "#F97316" },
    { id: "usr-5", label: "정다은", color: "#10B981" },
  ],
  funnels: [
    { id: "fn-top", label: "Top-Funnel", color: "#4F8EF7" },
    { id: "fn-mid", label: "Mid-Funnel", color: "#8B5CF6" },
    { id: "fn-bot", label: "Bottom-Funnel", color: "#EC4899" },
  ],
};

export const mockTasks: Task[] = [
  {
    id: "task-1",
    content: "홈페이지 랜딩 페이지 리디자인",
    importanceId: "imp-high",
    statusId: "st-inprog",
    assigneeId: "usr-1",
    comment: "UX 리서치 결과 반영 필요. 모바일 우선 설계 요청.",
    startDate: relDate(-14),
    dueDate: relDate(7),
    funnelId: "fn-top",
    createdAt: relDate(-20),
  },
  {
    id: "task-2",
    content: "SNS 광고 캠페인 A/B 테스트",
    importanceId: "imp-high",
    statusId: "st-inprog",
    assigneeId: "usr-2",
    comment: "Instagram, Facebook 채널 병행 테스트. CTR 목표 3.5% 이상.",
    startDate: relDate(-10),
    dueDate: relDate(14),
    funnelId: "fn-top",
    createdAt: relDate(-15),
  },
  {
    id: "task-3",
    content: "회원가입 프로세스 간소화",
    importanceId: "imp-high",
    statusId: "st-done",
    assigneeId: "usr-3",
    comment: "3단계 → 1단계 소셜 로그인 전환 완료. 가입 완료율 41% 향상.",
    startDate: relDate(-30),
    dueDate: relDate(-5),
    funnelId: "fn-mid",
    createdAt: relDate(-35),
  },
  {
    id: "task-4",
    content: "이메일 온보딩 시퀀스 개선",
    importanceId: "imp-mid",
    statusId: "st-inprog",
    assigneeId: "usr-4",
    comment: "7일 드립 캠페인 → 활성화율 측정 필요.",
    startDate: relDate(-7),
    dueDate: relDate(21),
    funnelId: "fn-mid",
    createdAt: relDate(-10),
  },
  {
    id: "task-5",
    content: "상품 검색 UI 개선",
    importanceId: "imp-mid",
    statusId: "st-wait",
    assigneeId: "usr-5",
    comment: "필터 기능 추가 및 검색 자동완성 구현 예정.",
    startDate: relDate(5),
    dueDate: relDate(30),
    funnelId: "fn-mid",
    createdAt: relDate(-3),
  },
  {
    id: "task-6",
    content: "결제 페이지 로딩 속도 개선",
    importanceId: "imp-high",
    statusId: "st-inprog",
    assigneeId: "usr-1",
    comment: "현재 LCP 4.2초 → 목표 1.8초 이하. Next.js Image 최적화 적용.",
    startDate: relDate(-5),
    dueDate: relDate(10),
    funnelId: "fn-bot",
    createdAt: relDate(-8),
  },
  {
    id: "task-7",
    content: "장바구니 이탈 방지 팝업 구현",
    importanceId: "imp-mid",
    statusId: "st-wait",
    assigneeId: "usr-2",
    comment: "5분 이상 비활성 시 할인 쿠폰 팝업 노출 전략.",
    startDate: relDate(10),
    dueDate: relDate(35),
    funnelId: "fn-bot",
    createdAt: relDate(-2),
  },
  {
    id: "task-8",
    content: "리타겟팅 광고 셋업",
    importanceId: "imp-low",
    statusId: "st-done",
    assigneeId: "usr-3",
    comment: "GA4 → Meta Pixel 연동 완료. 방문자 세그먼트 3개 구성.",
    startDate: relDate(-40),
    dueDate: relDate(-15),
    funnelId: "fn-top",
    createdAt: relDate(-45),
  },
  {
    id: "task-9",
    content: "고객 후기 및 신뢰 섹션 추가",
    importanceId: "imp-low",
    statusId: "st-done",
    assigneeId: "usr-4",
    comment: "별점 4.7 / 후기 120건 노출. 소셜 프루프 강화 완료.",
    startDate: relDate(-25),
    dueDate: relDate(-10),
    funnelId: "fn-mid",
    createdAt: relDate(-28),
  },
  {
    id: "task-10",
    content: "프로모션 코드 시스템 구현",
    importanceId: "imp-high",
    statusId: "st-hold",
    assigneeId: "usr-5",
    comment: "법무팀 검토 대기 중. 쿠폰 중복 사용 정책 확정 후 재개 예정.",
    startDate: relDate(20),
    dueDate: relDate(50),
    funnelId: "fn-bot",
    createdAt: relDate(-1),
  },
  {
    id: "task-11",
    content: "모바일 앱 푸시 알림 설정",
    importanceId: "imp-mid",
    statusId: "st-wait",
    assigneeId: "usr-1",
    comment: "FCM 토큰 관리 구조 설계 필요. AOS/iOS 분리 대응.",
    startDate: relDate(15),
    dueDate: relDate(45),
    funnelId: "fn-top",
    createdAt: relDate(-1),
  },
  {
    id: "task-12",
    content: "결제 완료 후 업셀 전략 구현",
    importanceId: "imp-mid",
    statusId: "st-inprog",
    assigneeId: "usr-2",
    comment: "주문 완료 페이지에서 관련 상품 추천 카루셀 노출.",
    startDate: relDate(-3),
    dueDate: relDate(18),
    funnelId: "fn-bot",
    createdAt: relDate(-5),
  },
];

export const kpiCards: KPICard[] = [
  {
    id: "kpi-1",
    title: "누적 유입",
    value: "128,540",
    change: 12.3,
    changeLabel: "전월 대비",
    icon: "Users",
    color: "#4F8EF7",
    bgColor: "rgba(79,142,247,0.12)",
  },
  {
    id: "kpi-2",
    title: "최종 전환율",
    value: "3.2%",
    change: 0.4,
    changeLabel: "전월 대비 +0.4%p",
    icon: "TrendingUp",
    color: "#10B981",
    bgColor: "rgba(16,185,129,0.12)",
  },
  {
    id: "kpi-3",
    title: "CAC",
    value: "₩24,500",
    change: -8.2,
    changeLabel: "전월 대비 절감",
    icon: "DollarSign",
    color: "#F59E0B",
    bgColor: "rgba(245,158,11,0.12)",
  },
  {
    id: "kpi-4",
    title: "ROAS",
    value: "320%",
    change: 15.5,
    changeLabel: "전월 대비",
    icon: "BarChart2",
    color: "#8B5CF6",
    bgColor: "rgba(139,92,246,0.12)",
  },
  {
    id: "kpi-5",
    title: "신규 가입자",
    value: "8,420",
    change: 5.7,
    changeLabel: "전월 대비",
    icon: "UserPlus",
    color: "#06B6D4",
    bgColor: "rgba(6,182,212,0.12)",
  },
  {
    id: "kpi-6",
    title: "평균 주문금액",
    value: "₩67,800",
    change: 3.1,
    changeLabel: "전월 대비",
    icon: "ShoppingCart",
    color: "#EC4899",
    bgColor: "rgba(236,72,153,0.12)",
  },
];

export const funnelStages: FunnelStage[] = [
  { id: "fs-1", name: "유입 (Landing)", count: 128540, color: "#4F8EF7" },
  { id: "fs-2", name: "회원가입 (Sign Up)", count: 42310, color: "#8B5CF6" },
  { id: "fs-3", name: "상품검색 (Search)", count: 28640, color: "#06B6D4" },
  { id: "fs-4", name: "결제시도 (Checkout)", count: 6890, color: "#F59E0B" },
  { id: "fs-5", name: "최종결제 (Purchase)", count: 4110, color: "#10B981" },
];

export const bottlenecks: Bottleneck[] = [
  {
    id: "bn-1",
    stage: "유입 → 회원가입",
    issue: "회원가입 이탈율 67.1%",
    impact: "high",
    metric: "67.1% 이탈",
    description:
      "소셜 로그인 미지원, 필드 수 과다(11개), 약관 동의 복잡성으로 인한 이탈. 가입 페이지 접근 후 3초 내 이탈 비율 42%.",
  },
  {
    id: "bn-2",
    stage: "상품검색 → 결제시도",
    issue: "검색 후 결제 전환율 24.1%",
    impact: "high",
    metric: "75.9% 이탈",
    description:
      "검색 결과 필터 부재, 상품 상세 페이지 로딩 지연(3.8초), 리뷰 정보 부족으로 구매 신뢰도 저하.",
  },
  {
    id: "bn-3",
    stage: "결제시도 → 최종결제",
    issue: "결제 완료율 59.6%",
    impact: "medium",
    metric: "40.4% 이탈",
    description:
      "결제 페이지 LCP 4.2초, 간편결제 옵션 부족, 배송비 정책 불명확으로 마지막 단계 이탈 발생.",
  },
  {
    id: "bn-4",
    stage: "회원가입 → 상품검색",
    issue: "가입 후 검색 전환율 67.7%",
    impact: "low",
    metric: "32.3% 이탈",
    description:
      "온보딩 이메일 오픈율 18%, 가입 직후 상품 탐색 유도 CTA 부재. 개선 가능성 높음.",
  },
];

export const initialTodos: TodoItem[] = [
  {
    id: "todo-1",
    text: "회원가입 소셜 로그인 (Google/Kakao) 도입",
    completed: false,
    priority: "high",
    relatedStage: "유입 → 회원가입",
  },
  {
    id: "todo-2",
    text: "가입 필드 5개 이하로 축소",
    completed: true,
    priority: "high",
    relatedStage: "유입 → 회원가입",
  },
  {
    id: "todo-3",
    text: "상품 검색 자동완성 및 필터 기능 추가",
    completed: false,
    priority: "high",
    relatedStage: "상품검색 → 결제시도",
  },
  {
    id: "todo-4",
    text: "결제 페이지 LCP 1.8초 이하 달성",
    completed: false,
    priority: "high",
    relatedStage: "결제시도 → 최종결제",
  },
  {
    id: "todo-5",
    text: "카카오페이/토스 간편결제 연동",
    completed: false,
    priority: "medium",
    relatedStage: "결제시도 → 최종결제",
  },
  {
    id: "todo-6",
    text: "가입 완료 후 즉시 상품 추천 페이지 노출",
    completed: false,
    priority: "medium",
    relatedStage: "회원가입 → 상품검색",
  },
  {
    id: "todo-7",
    text: "상품 상세 페이지 로딩 3초 → 1.5초 최적화",
    completed: true,
    priority: "medium",
    relatedStage: "상품검색 → 결제시도",
  },
  {
    id: "todo-8",
    text: "배송비 무료 조건 메인 배너 노출",
    completed: false,
    priority: "low",
    relatedStage: "결제시도 → 최종결제",
  },
];
